-- Flyway migration V1: initial schema for Fintrix
-- This migration is designed to work on PostgreSQL and H2 (test) in PostgreSQL mode.

-- Users
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    email VARCHAR(180) NOT NULL,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_users_email ON users(email);

-- Workspaces
CREATE TABLE IF NOT EXISTS workspaces (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    owner_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL
);

-- Memberships
CREATE TABLE IF NOT EXISTS memberships (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    workspace_id BIGINT NOT NULL,
    role VARCHAR(20) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_memberships_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_memberships_workspace FOREIGN KEY (workspace_id) REFERENCES workspaces(id)
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_memberships_user_workspace ON memberships(user_id, workspace_id);

-- Expenses
CREATE TABLE IF NOT EXISTS expenses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(150) NOT NULL,
    amount NUMERIC(14,2) NOT NULL,
    category VARCHAR(80) NOT NULL,
    date DATE NOT NULL,
    user_id BIGINT NOT NULL,
    workspace_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_expenses_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_expenses_workspace FOREIGN KEY (workspace_id) REFERENCES workspaces(id)
);

CREATE INDEX IF NOT EXISTS idx_expenses_user_id ON expenses(user_id);
CREATE INDEX IF NOT EXISTS idx_expenses_workspace_id ON expenses(workspace_id);

-- Transactions (income/expense record)
CREATE TABLE IF NOT EXISTS transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    amount NUMERIC(14,2) NOT NULL,
    type VARCHAR(20) NOT NULL,
    category VARCHAR(80) NOT NULL,
    date DATE NOT NULL,
    description VARCHAR(500),
    user_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_transactions_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE INDEX IF NOT EXISTS idx_transactions_user_id ON transactions(user_id);

-- Borrow transactions
CREATE TABLE IF NOT EXISTS borrow_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    amount NUMERIC(14,2) NOT NULL,
    borrower_id BIGINT NOT NULL,
    lender_id BIGINT NOT NULL,
    workspace_id BIGINT NOT NULL,
    description VARCHAR(255) NOT NULL,
    status VARCHAR(20) NOT NULL,
    transaction_date DATE NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_borrow_transactions_borrower FOREIGN KEY (borrower_id) REFERENCES users(id),
    CONSTRAINT fk_borrow_transactions_lender FOREIGN KEY (lender_id) REFERENCES users(id),
    CONSTRAINT fk_borrow_transactions_workspace FOREIGN KEY (workspace_id) REFERENCES workspaces(id)
);

CREATE INDEX IF NOT EXISTS idx_borrow_transactions_workspace_id ON borrow_transactions(workspace_id);
CREATE INDEX IF NOT EXISTS idx_borrow_transactions_borrower_id ON borrow_transactions(borrower_id);
CREATE INDEX IF NOT EXISTS idx_borrow_transactions_lender_id ON borrow_transactions(lender_id);

-- Password reset tokens
CREATE TABLE IF NOT EXISTS password_reset_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token VARCHAR(120) NOT NULL,
    type VARCHAR(32) NOT NULL DEFAULT 'RESET_LINK',
    user_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    used BOOLEAN NOT NULL,
    attempts INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT fk_password_reset_tokens_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_prt_token ON password_reset_tokens(token);

